name: weverefy
description: "A new Flutter project."
publish_to: 'none' 

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7
  cached_network_image: ^3.2.2
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.6
  dio: ^5.1.2
  external_app_launcher: ^4.0.0
  file_picker: ^6.1.1
  flutter_screenutil: ^5.8.1
  flutter_svg: ^2.0.6
  flutter_web_browser: ^0.17.1
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.4
  image_cropper: ^7.0.5
  image_picker: ^1.0.4
  injectable: ^2.3.0
  intl: ^0.17.0
  intl_phone_field: ^3.1.0
  jiffy: ^5.0.0
  json_annotation: ^4.7.0
  local_auth: ^2.1.7
  number_text_input_formatter: ^1.0.0+3
  overlay_support: ^2.1.0
  package_info_plus: ^4.0.1
  page_transition: ^2.0.9
  path_provider: ^2.0.11
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.1.1
  pull_to_refresh_flutter3: ^2.0.1
  screenshot: ^2.1.0
  share_plus: ^7.0.1
  flutter_keyboard_visibility: ^6.0.0
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  stacked: ^3.2.7
  stacked_hooks: ^0.2.2
  stacked_services: ^1.0.2
  url_launcher: ^6.1.7
  circular_profile_avatar: ^2.0.5
  win32: ^5.0.9
  http: ^1.2.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: ^6.7.1
  stacked_generator: ^1.5.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/appIcon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/appIcon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/appIcon.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/

  
  fonts:
    - family: Aeonik
      fonts:
        - asset: fonts/AeonikTRIAL-Regular.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
